#175 create table and api endpoint for user side dishes
erikzimmermann/mensa-today pull request #176
Opened 2022-12-28 09:51 UTC by martenjostmann

2022-12-28 10:02 UTC, erikzimmermann requested changes

2022-12-28 10:02 UTC, erikzimmermann commented on backend/mensa/views.py
> +                side = dish['side']
What about a list of side dishes? E.g. when you take two side dishes...

2022-12-31 09:01 UTC, erikzimmermann requested changes

2022-12-31 09:01 UTC, erikzimmermann commented on backend/mensa_recommend/serializers.py
> +            When the context 'include_sides' is True then side dishes should be included.
Does side dishes (in general) mean that it just forwards the available side dishes? And selected therefore that the returned sides are only selected ones?

2022-12-31 09:41 UTC, martenjostmann commented on backend/mensa_recommend/serializers.py
> +            When the context 'include_sides' is True then side dishes should be included.
I don't really understand your question.

2022-12-31 10:31 UTC, erikzimmermann requested changes

2022-12-31 10:31 UTC, erikzimmermann commented on backend/mensa_recommend/serializers.py
> +                  "priceStudent", "priceEmployee", "side_dishes", "side_selected"]
I'm relatively sure the variable "fields" is a static one... Did you test multiple runs where you first have a context that deletes e.g. the name "side_dishes" and then another run where you want "side_dishes" included?

My guess is that "fields" will be the old instance without "side_dishes".

2022-12-31 10:45 UTC, martenjostmann commented on backend/mensa_recommend/serializers.py
> +                  "priceStudent", "priceEmployee", "side_dishes", "side_selected"]
The output looks as expected. So I guess this is not a problem. For instance in the first run "side_selected" will be deleted and in the recursive run "side_selected" is not deleted. Same for "side_dishes". I would assume that if "fields" is really static a deletion of an instance results in an error.

2022-12-31 11:12 UTC, erikzimmermann approved these changes

2023-01-01 10:41 UTC, merged