WIP: Side dish recommendation + Performance improvement
erikzimmermann/mensa-today pull request #192
Opened 2023-01-12 22:27 UTC by erikzimmermann

2023-01-13 16:18 UTC, erikzimmermann commented
Closes #191

2023-01-14 12:18 UTC, martenjostmann requested changes

2023-01-14 12:18 UTC, martenjostmann commented on backend/mensa_recommend/source/recommendation/recommender.py
> +                if current is None or score > current[1]:
Shouldn't it be score < current[1] ?

2023-01-14 12:18 UTC, martenjostmann commented on backend/mensa_recommend/source/recommendation/recommender.py
>          """Load the dish plan from the database.
Some more comments would be nice. When I understand the function right it is not just loading dishes but also filtering same dishes with higher distance to the mensa

2023-01-14 12:18 UTC, martenjostmann commented on backend/mensa_recommend/source/processing/conditions.py
> +            .seconds < self._lifetime
```suggestion
        result = self._timestamp is not None and 
        (now - self._timestamp).seconds < self._lifetime
```

2023-01-14 12:18 UTC, martenjostmann commented on backend/mensa_recommend/source/recommendation/recommender.py
> +        return self._cache[broad_zip][t][1]
More comments would be nice for better readability

2023-01-14 12:18 UTC, martenjostmann commented on backend/mensa_recommend/source/recommendation/recommender.py
>          first demo and a most viable product.
I think we can remove this now.

2023-01-14 12:18 UTC, martenjostmann commented on backend/mensa_recommend/source/recommendation/recommender.py
> +    _weather = WeatherCache()
Maybe a comment describing where these static variables are for

2023-01-14 12:18 UTC, martenjostmann commented on backend/requirements.txt
> +joblib==1.2.0
is joblib used right now?

2023-01-14 12:26 UTC, erikzimmermann commented on backend/mensa_recommend/source/recommendation/recommender.py
> +                if current is None or score > current[1]:
I had it before and the score is between 0..1. The higher the better.

2023-01-15 18:45 UTC, martenjostmann approved these changes

2023-01-15 22:21 UTC, merged